#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "str_replace.h"
#include "create.h"

char name[100];
char filename[103];
unsigned int duration;

void setName(){
	char confirm;
	printf("Wie lautet der Name der Reise?");
	scanf("%s",&name);
	printf("Der Reisename ist: %s\n", name);
	printf("Ist das korrekt? (y|n)\n");
	while((getchar())!='\n');
	confirm=getchar();
	if(confirm=='y'){
		return;
	}
	printf("Okay. Wir versuchens nochmal...\n------------------\n\n\n");
	setName();
}
void setDuration(){
	char confirm;
	printf("Wie lange dauert die Reise?\n");
	scanf("%3d",&duration);
	printf("Die Reise dauert %d Tage.\n", duration);
	printf("Ist das korrekt? (y|n)\n");
	while((getchar())!='\n');
	confirm=getchar();
	if(confirm=='y'){
		return;
	}
	printf("Okay. Wir versuchens nochmal...\n------------------\n\n\n");
	setDuration();
}
void buildList(){
	FILE *file;
	strcpy(filename,name);
	strcat(filename,".md");

	file=fopen(filename,"w");
	fputs("",file);
	fclose(file);

	file = fopen(filename,"a");
	printf("%s\n",name);
	fprintf(file,"# %s  \n\n",name);

	fprintf(file," - [ ] %3d Tshirts  \n",duration+1);
	fprintf(file," - [ ] %3d LongShirts / Hoodies  \n",(int)ceil(duration/3));
	fputs(" - [ ] >1 Jeans (lang)  \n",file);
	fprintf(file," - [ ] %3d Hosen  \n",(int)ceil(duration/3)-1);
	fprintf(file," - [ ] %3d Unterhosen  \n",duration+1);
	fprintf(file," - [ ] %3d BH  \n",(int)ceil(duration/3));
	fprintf(file," - [ ] %3d Socken  \n",duration+1);
	fputs(" - [ ] Jacke  \n\n",file);

	fputs(" - [ ] Schlafhose  \n",file);
	fputs(" - [ ] Schlafshirt  \n",file);
	fputs(" - [ ] Kuscheltier  \n\n",file);

	fputs(" - [ ] 1 Duschgel  \n",file);
	fputs(" - [ ] 1 Schampoo  \n",file);
	fputs(" - [ ] 1 Deo  \n",file);
	fputs(" - [ ] 1 Zahnbürste  \n",file);
	fputs(" - [ ] 1 Zahnpasta  \n",file);
	fputs(" - [ ] 1 Bürste  \n",file);
	fputs(" - [ ] 1 Haarspray  \n",file);
	fputs(" - [ ] 1 Haargel  \n",file);
	fputs(" - [ ] 1 Rasierer  \n",file);
	fputs(" - [ ] Makeup  \n\n",file);

	fputs(" - [ ] >1 Ladekabel  \n",file);
	fputs(" - [ ] >1 Kopfhörer  \n",file);
	fputs(" - [ ] Powerbank  \n\n",file);

	fputs(" - [ ] Reisepass  \n",file);
	fputs(" - [ ] Reiseunterlagen (Flugtickets,etc.)  \n",file);
	fputs(" - [ ] Einverständniserklärung der Eltern  \n\n",file);

	fputs("# Für Sommerurlaube  \n\n",file);

	fputs(" - [ ] Badekleidung (Bikini, Badehose, etc.)  \n",file);
	fputs(" - [ ] Sonnencreme  \n",file);
	fputs(" - [ ] AfterSun Lotion  \n\n",file);

	fputs("# Für Winterurlaube  \n\n",file);

	fputs(" - [ ] Handschuhe  \n",file);
	fputs(" - [ ] Schaal  \n\n",file);

	fputs("# Notation  \n\n",file);

	fputs(">x bedeutet mindestens x Strück  \n",file);
	fputs("<x bedeztet maximal x Stück  \n\n",file);

	fputs("This was generated by the Urlaubsplaner written by Pascal Gläßer (github.com/otakupasi)  ",file);

	fclose(file);
}

int main(int argc, char const *argv[])
{
	setName();
	setDuration();
	printf("Generating Output file\n");
	buildList();
	prinf("Finished with Exit Code 0\n\n");
	/* code */
	return 0;
}
